platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'iCarousel', '~> 1.8.1'
pod 'Reachability',  '~> 3.0.0'
pod 'RegexKitLite'
pod 'HMSegmentedControl'
pod 'MDCSwipeToChoose'
pod 'MJExtension'
pod "Qiniu", "~> 7.0"
pod 'MJRefresh'
pod 'PEPhotoCropEditor'
